language: python
python:
  - "3.6"
before_install:
  - export TZ=EST
  - sudo apt-get update
  - pip install pycodestyle codecov
  - pip install -r requirements.txt
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - coverage run --source=. -m pytest
  - coverage report -m
after_success:
  - codecov
